[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "text-summarizer-system"
version = "0.1.0"
description = "Text Summarization System (FastAPI + Streamlit)"
requires-python = ">=3.10"